### ISSUE TITLE
Bug: functionToCall is not a function

### ISSUE THREAD

**Issue by mikepsinn** [polywrap/agent-learning-demo#45]
Hi, I get the following error with node v18.16.0. Any suggestions?

```
PS C:\code\PolyGPT> yarn start
> Fetching wrap library index @ https://raw.githubusercontent.com/polywrap/polygpt/dev/wrap-library
Support: https://discord.polywrap.io
Known Wraps:
[
  "ethers",
  "http",
  "ipfs",
  "filesystem",
  "web-scraper",
  "ens",
  "safe-factory"
]
Please enter your main goal: 

Summarize the contents of https://polywrap.io in 100 words, and write what you learn to a polywrap.md file
```
```
Do you wish to execute the following function?

http.get ({
  "url": "https://polywrap.io"
})

(Y/N)
y
Unrecoverable error encountered.
Message: functionToCall is not a function
```

**Comment by rihp** [comment]
Thanks for the report, I'll try to reproduce this, the `http.get` structure is what looks weird here. were you able to reproduce it?

**Comment by rihp** [comment]
It looks like it's the newer 16k token model hallucinating, i was able to reproduce with GPT3.5, have you tried GPT4? It did catch the right function for me


Please enter your main goal: Summarize the contents of https://polywrap.io in 100 words, and write what you learn to a polywrap.md file
Do you wish to execute the following function?

```
LearnWrap ({
  "name": "web-scraper"
})
```

(Y/N)
y

> 🧠 Learnt a wrap: web-scraper
> Description: Query the internet and scrape its contents 
> Repo: https://github.com/polywrap/web-scraper

Do you wish to execute the following function?

```
InvokeWrap ({
  "uri": "ipfs/QmXKA6qc3TMiBZn5DyydYwdc9o2uSShqFdV7yTgYjF2xdu",
  "method": "get_text",
  "args": {
    "url": "https://polywrap.io"
  }
})
```

**Comment by rihp** [comment]
One potential solution for these cases is implementing a try/catch when the function doesnt exist, we dont exit out of the agent loop

**Comment by dOrgJelli** [comment]
I remember seeing this while using GPT3, but with 4 it is able to properly understand the correct function to call.

I think we should:
* show warning when GPT3 is being used, stating “it is highly recommended to use GPT4 for best results”.
* Add a try catch so it doesn’t exit, but instead logs the error so the agent can try to recover.

**Comment by dOrgJelli** [comment]
Fixed here: https://github.com/polywrap/PolyGPT/pull/67
