### ISSUE TITLE
Feat: Comply with Agent Protocol

### ISSUE THREAD

**Issue by rihp** [polywrap/agent-learning-demo#52]
3 members of the autogpt community have suggested we implement their agent protocol in order to run benchmarks for the agent

Here is the repo and are offering guidance to get it implemented
https://github.com/e2b-dev/agent-protocol/#javascripttypescript-sdk

If it helps, here's for example how smol developer implements it (smol developer has its own SDK)
https://github.com/smol-ai/developer/blob/main/smol_dev/api.py

More examples can be found here https://github.com/e2b-dev/agent-protocol/blob/main/README.md#open-source-agents-and-projects-that-have-adopted-agent-protocol

**Comment by rihp** [comment]
from @dOrgJelli:

The "agent-protocol" allows you to interact with any agent via HTTP requests
Auto-GPT devs built this to run automated tests against agents
You can find a list of agent tests here: https://github.com/Significant-Gravitas/Auto-GPT-Benchmarks
They "score" the agents being tested here, which can help us show our unique benefits!

Implementing the "agent-protocol" into PolyGPT is fairly simple, would only require a day of work to get it working.

Benefits for us? Could help us showcase PolyGPT abilities alongside other popular agents, helping gain validity.

**Comment by rihp** [comment]
![image](https://github.com/polywrap/PolyGPT/assets/12145726/6e220c0e-4757-4482-a72e-e3edae499590)

Sample of what the bencharking looks like right now, it looks like AutoGPT would have to create a new category to measure the capabilities of PolyGPT

**Comment by dOrgJelli** [comment]
This work has been completed here: https://github.com/polywrap/PolyGPT/pull/61
