### ISSUE TITLE
Feat: Web Scrapper wrap

### ISSUE THREAD

**Issue by rihp** [polywrap/agent-learning-demo#58]
The Web scrapper wrap is a mvp of the a web scrapper, however it comes with a lot of html and css code that shoudlnt be there and wastes tokens and requires more time to process. we should be able to fix this to improve the UX

Here is the repo for the wrap 
https://github.com/polywrap/web-scraper

**Comment by dOrgJelli** [comment]
The web-scraper has been working so far for our needs. It can be updated as needed, so I'm going to close this as complete.
