### ISSUE TITLE
Feat: Use a Wrap library that we have locally

### ISSUE THREAD

**Issue by rihp** [polywrap/agent-learning-demo#63]
currently we only fetch wraps using http and the env variable 

WRAP_LIBRARY_URL="https://raw.githubusercontent.com/polywrap/polygpt/dev/wrap-library"

we should be able to debug more simply if we can set the wraplibrary as a local file

**Comment by rihp** [comment]
suggested by @nerfZael

**Comment by dOrgJelli** [comment]
Work completed here: https://github.com/polywrap/PolyGPT/pull/66
